language: node_js
install: skip
node_js:
- '10.0'
dist: trusty
sudo: false

addons:
  ssh_known_hosts:
    - 172.104.26.28

before_install:
- openssl aes-256-cbc -K $encrypted_539b0e080071_key -iv $encrypted_539b0e080071_iv
  -in scripts/gatsby-deploy.enc -out scripts/gatsby-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/gatsby-deploy ~/.ssh/gatsby-deploy
- chmod 600 ~/.ssh/gatsby-deploy
- ssh-add ~/.ssh/gatsby-deploy
- echo -e "Host 172.104.26.28\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master


